/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker-configuration.d.ts` (hash: b1379ff348c4811248c6c3f73d78257d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "HarryAgent";
	}
	interface Env {
		MARKET_DB: D1Database;
		HARRY_MEMORY: VectorizeIndex;
		CALCULATOR_BASE_URL: "http://127.0.0.1:3000";
		HarryAgent: DurableObjectNamespace<import("./src/index").HarryAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CALCULATOR_BASE_URL">> {}
}
